spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: ERROR
